# Generated by Django 4.1.7 on 2023-02-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isVegan', models.BooleanField()),
                ('hasDairy', models.BooleanField()),
                ('hasNuts', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredient', models.ManyToManyField(to='recipes.ingredients')),
            ],
            options={
                'verbose_name_plural': 'Recipes',
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
