# Generated by Django 4.1.7 on 2023-02-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_ingredients_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='hasGluten',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
